apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: nextcloud-aio-database-dump
  name: nextcloud-aio-database-dump
  namespace: "{{ .Values.NAMESPACE }}"
spec:
  {{- if .Values.STORAGE_CLASS }}
  storageClassName: {{ .Values.STORAGE_CLASS }}
  {{- if .Values.STORAGE_RECLAIM_POLICY }}
  persistentVolumeReclaimPolicy: {{ .Values.STORAGE_RECLAIM_POLICY }}
  {{- end }}
  {{- if .Values.STORAGE_LOCAL_BASE_PATH }}
  local:
    path: {{ .Values.STORAGE_LOCAL_BASE_PATH }}/nextcloud-aio-database-dump
  {{- end }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.DATABASE_DUMP_STORAGE_SIZE }}
